# Generated by Django 2.2.17 on 2021-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/1234.jpg', upload_to='products_images'),
        ),
    ]
