# Generated by Django 2.2.17 on 2021-02-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210131_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/default_img/1234.jpg', upload_to='products_images'),
        ),
    ]
